### ISSUE TITLE
No module named 'secretstorage'

### ISSUE THREAD

**Issue by duckworth** [robinvandernoord/lib2fas-python#3]
Hi @robinvandernoord,  I think the dependency secretstorage might be missing in the 0.1.4 release. I have tried installing lib2fas==0.1.4 in a new virtualenv and it fails with: 
`ModuleNotFoundError: No module named 'secretstorage'. `

I don't see it listed in dependencies?

**Comment by robinvandernoord** [comment]
`SecretStorage` is a dependency of [keyring](https://github.com/jaraco/keyring).
It seems keyring only installs 'secretstorage' for Linux, but I import it because of type hinting. I will change it to a typing-only import, so it doesn't have to be installed on run time. I haven't tested on Mac or Windows at all, I assume you're on one of those platforms?

**Comment by duckworth** [comment]
Yeah, I am running on mac. Thanks, I will give it a try.

**Comment by duckworth** [comment]
Hmm, now I get an error, ModuleNotFoundError: No module named 'typing_extensions'

**Comment by robinvandernoord** [comment]
Oops, I assumed indirect dependencies always to be installed but they seem to differ per platform/Python-version so I'll add them explicitly!

**Comment by robinvandernoord** [comment]
When did you get this error? typing_extensions is only used by the CLI part, if you were using the core lib and got this error I'm very confused.
I added the dependency to 1.0.2 of [robinvandernoord/2fas-python](https://github.com/robinvandernoord/2fas-python)

**Comment by duckworth** [comment]
ok, took a bit to narrow down but it seems to only happen on python 3.12.2 (the latest that homebrew installs by default). Running the basic example in the readme with lib2fas==0.1.5 causes:
`ModuleNotFoundError: No module named 'typing_extensions'`
on the line:
`import lib2fas`

running it on python 3.11.8 works fine.

**Comment by robinvandernoord** [comment]
Thanks for testing this out. This turned out to be an issue of another project of mine (configuraptor), which is a dependency of lib2fas. I patched that package and released lib2fas 0.1.6, which works on my 3.12 installation (albeit on Linux, not Mac)
